
rbac:
  create: false

prometheus:
  fullnameOverride: prometheus
  ingress:
    enabled: true
    hosts: [prometheus.myk8s]

alertmanager:
  fullnameOverride: alertmanager
  ingress:
    enabled: true
    hosts: [alertmanager.myk8s]

grafana:
  fullnameOverride: grafana
  ingress:
    enabled: true
    hosts: [grafana.myk8s]
  grafana.ini:
    users:
      viewers_can_edit: true
    auth:
      disable_login_form: true
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
      org_role: Admin
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'myk8s'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/myk8s
  dashboards:
    myk8s:
      kubernetes-cluster:
        gnetId: 6417
        revision: 1
        datasource: Prometheus

coreDns:
  enabled: false

kubeDns:
  enabled: false

kubeEtcd:
  enabled: false
