apiVersion: v1
kind: Service
metadata:
  name: myk8s-dns
  namespace: {{ .Release.namespace }}
spec:
  ports:
  - name: dns
    nodePort: {{ .Values.externalDns.nodePort }}
    port: 53
    protocol: UDP
    targetPort: 53
  selector:
    app: coredns
  type: NodePort
